CREATE TABLE user
(
    id         CHAR(26)     NOT NULL COMMENT 'ユーザーID(ulid)',
    name       VARCHAR(20)  NOT NULL COMMENT 'ユーザー名',
    email      VARCHAR(254) NOT NULL COMMENT 'メールアドレス',
    password   CHAR(60)     NOT NULL COMMENT 'パスワード',
    created_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
    updated_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時'
);

CREATE TABLE medicine
(
    id      CHAR(26)     NOT NULL COMMENT 'ID',
    user_id CHAR(26)     NOT NULL COMMENT 'ユーザーID',
    name    VARCHAR(255) NOT NULL COMMENT '名前',
    note    VARCHAR(255) NOT NULL COMMENT 'メモ'
);

CREATE TABLE medicine_history
(
    medicine_id CHAR(26) NOT NULL COMMENT 'ID',
    taken_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '服用日時',
    created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
    updated_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時'
);