version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./
        target: /app
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    restart: always
    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: "cycle_note"
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      TZ: Asia/Tokyo
    volumes:
      - type: volume
        source: db-volume
        target: /var/lib/init
      - type: bind
        source: ./init
        target: /docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  db-volume: null